force-app/main/campusAlert/objects/Facility_Event__c/Facility_Event__c.object-meta.xml
<CustomObject>
    <label>Facility Event</label>
    <nameField>
        <label>Facility Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/campusAlert/objects/Facility_Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Facility Events</relationshipLabel>
    <relationshipName>Facility_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/campusAlert/objects/Facility_Event_Participation__c/Facility_Event_Participation__c.object-meta.xml
<CustomObject>
    <label>Facility Event Participation</label>
    <nameField>
        <label>Facility Event Participation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facility Event Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/campusAlert/objects/Facility_Event_Participation__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Facility</label>
    <referenceTo>Facility__c</referenceTo>
    <relationshipLabel>Facility Event Participations</relationshipLabel>
    <relationshipName>Facility_Event_Participations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/campusAlert/objects/Facility_Event_Participation__c/fields/Facility_Event__c.field-meta.xml
<CustomField>
    <fullName>Facility_Event__c</fullName>
    <label>Facility Event</label>
    <referenceTo>Facility_Event__c</referenceTo>
    <relationshipLabel>Facility Event Participations</relationshipLabel>
    <relationshipName>Facility_Event_Participations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/campusAlert/classes/CampaignFacilityEventController.cls
public with sharing class CampaignFacilityEventController {

    public static List<FacilityModel> getFacilityModels(Id campaignId) {
        try {
            Set<Id> facilityIds = CampaignFacilityEventController.getFacilityIdsFromCampaignId(campaignId);

            if(facilityIds.isEmpty()) {
                return new List<FacilityModel>();
            }

            List<Facility__c> allFacilities = CampaignFacilityEventController.getAllFacilitiesFromParentFacilityIds(facilityIds);

            if(allFacilities.isEmpty()) {
                return new List<FacilityModel>();
            }

            List<FacilityModel> facilityModels = CampaignFacilityEventController.getFacilityModelsFromFacilities(allFacilities);
            return facilityModels;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    //Gets all facility ids from Campaign -> Facility Even -> Facility Event Participation -> Facility
    public static Set<Id> getFacilityIdsFromCampaignId(Id campaignId) {
        Map<Id,Facility_Event__c> facilityEvents = new Map<Id,Facility_Event__c>([
            SELECT Id
            FROM Facility_Event__c
            WHERE Campaign__c = :campaignId]);
        
        if(facilityEvents.isEmpty()) {
            return new Set<Id>();
        }

        Map<Id,Facility_Event_Participation__c> facilityEventParticipations = new Map<Id,Facility_Event_Participation__c>([
            SELECT Id,
                Facility__c
            FROM Facility_Event_Participation__c
            WHERE Facility_Event__c IN :facilityEvents.keySet()
        ]);
        
        if(facilityEventParticipations.isEmpty()) {
            return new Set<Id>();
        }

        //Set to ensure uniqueness
        Set<Id> facilityIds = new Set<Id>();
        for(Facility_Event_Participation__c facilityEventParticipation : facilityEventParticipations.values()) {
            facilityIds.add(facilityEventParticipation.Facility__c);
        }
        return facilityIds;
    }

    //Gets all Facilities recursively in a list order of parent, child, grandchild, etc
    public static List<Facility__c> getAllFacilitiesFromParentFacilityIds(Set<Id> facilityIds) {
        //Map to permit for recursive keysets
        Map<Id, Facility__c> currentFacilities = new Map<Id, Facility__c>([
            SELECT Id,
                Name,
                Parent_Facility__c
            FROM Facility__c
            WHERE Id IN :facilityIds
        ]);

        //Use this for a deliberate iteration sort the map does not provide
        List<Facility__c> allFacilities = new List<Facility__c>();

        //Though this is an iteration for an arbitrary nesting, this should not exceed the SOQL query limits
        WHILE(currentFacilities.isEmpty() == false) {
            //This saves cycles as we will reenter the loop and apply similar logic
            allFacilities.addAll(currentFacilities.values());                
            currentFacilities = new Map<Id, Facility__c>([
                SELECT Id,
                    Name,
                    Parent_Facility__c
                FROM Facility__c
                WHERE Id IN :currentFacilities.keySet()
            ]);
        }

        return allFacilities;
    }

    //Gets all facilities starting from parent facilities in an ordered list
    public static List<FacilityModel> getFacilityModelsFromFacilities(List<Facility__c> allFacilities) {
        List<FacilityModel> baseFacilityModels = new List<FacilityModel>();
        Map<Id,FacilityModel> FacilityModelsByFacilityIds = new Map<Id,FacilityModel>();

        for(Facility__c currentFacility : allFacilities) {
            FacilityModel currentFacilityModel = new FacilityModel(currentFacility);

            if(currentFacility.Parent_Facility__c == null) {
                //parents go into the top-level list
                baseFacilityModels.add(currentFacilityModel);
                continue;
            }

            //children go into the parent's child list
            //We ensured a list order that guarantees the parent is already processed in the get facilities method
            FacilityModel parentFacilityModel = FacilityModelsByFacilityIds.get(currentFacility.Parent_Facility__c);
            parentFacilityModel.children.add(currentFacilityModel);
        }

        return baseFacilityModels;
    }
}